# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-13 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_num', models.CharField(max_length=5, unique=True, verbose_name='\u9009\u62e9\u9898\u7f16\u53f7')),
                ('course_title', models.CharField(max_length=50, unique=True, verbose_name='\u9009\u62e9\u9898\u9898\u76ee')),
                ('choice_A', models.CharField(blank=True, max_length=50, verbose_name='\u7b54\u6848A')),
                ('choice_B', models.CharField(blank=True, max_length=50, verbose_name='\u7b54\u6848B')),
                ('choice_C', models.CharField(blank=True, max_length=50, verbose_name='\u7b54\u6848C')),
                ('choice_D', models.CharField(blank=True, max_length=50, verbose_name='\u7b54\u6848D')),
                ('course_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='\u9009\u62e9\u9898\u7b54\u6848')),
                ('is_finish', models.BooleanField(default=False, verbose_name='\u5b8c\u6210\u7ec3\u4e60')),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898\u5e93',
                'verbose_name_plural': '\u9009\u62e9\u9898\u5e93',
            },
        ),
        migrations.CreateModel(
            name='Course_full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_num', models.IntegerField(unique=True, verbose_name='\u7f16\u7a0b\u9898\u7f16\u53f7')),
                ('course_title', models.CharField(max_length=50, unique=True, verbose_name='\u9009\u62e9\u9898\u9898\u76ee')),
                ('course_answer', models.CharField(max_length=1000, verbose_name='\u7f16\u7a0b\u9898\u7b54\u6848')),
                ('is_finish', models.BooleanField(default=False, verbose_name='\u5b8c\u6210\u7ec3\u4e60')),
            ],
            options={
                'verbose_name': '\u7f16\u7a0b\u9898\u5e93',
                'verbose_name_plural': '\u7f16\u7a0b\u9898\u5e93',
            },
        ),
        migrations.CreateModel(
            name='Course_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_num', models.IntegerField(unique=True, verbose_name='\u9879\u76ee\u9898\u7f16\u53f7')),
                ('course_title', models.CharField(max_length=50, unique=True, verbose_name='\u9879\u76ee\u9898\u9898\u76ee')),
                ('course_answer', models.CharField(max_length=1000, verbose_name='\u9879\u76ee\u9898\u7b54\u6848')),
                ('is_finish', models.BooleanField(default=False, verbose_name='\u5b8c\u6210\u7ec3\u4e60')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u9898\u5e93',
                'verbose_name_plural': '\u9879\u76ee\u9898\u5e93',
            },
        ),
        migrations.CreateModel(
            name='User_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_num', models.CharField(max_length=5, verbose_name='\u9009\u62e9\u9898\u7f16\u53f7')),
                ('user_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=5, null=True, verbose_name='\u7528\u6237\u9009\u62e9\u9898\u56de\u7b54')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237-\u9009\u62e9\u9898',
                'verbose_name_plural': '\u7528\u6237-\u9009\u62e9\u9898',
            },
        ),
        migrations.CreateModel(
            name='User_full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(default=None, max_length=1000, null=True, verbose_name='\u7528\u6237\u7f16\u7a0b\u9898\u56de\u7b54')),
                ('full_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.Course_full', to_field='full_num', verbose_name='\u7f16\u7a0b\u9898\u7f16\u53f7')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237-\u7f16\u7a0b\u9898',
                'verbose_name_plural': '\u7528\u6237-\u7f16\u7a0b\u9898',
            },
        ),
        migrations.CreateModel(
            name='User_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(default=None, max_length=10000, null=True, verbose_name='\u7528\u6237\u9879\u76ee\u9898\u56de\u7b54')),
                ('project_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.Course_project', to_field='project_num', verbose_name='\u9879\u76ee\u9898\u7f16\u53f7')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u7528\u6237-\u9879\u76ee',
                'verbose_name_plural': '\u7528\u6237-\u9879\u76ee',
            },
        ),
    ]
