# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-11 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20161113_2218'),
        ('onlinepractice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(verbose_name='\u9898\u76ee\u7f16\u53f7')),
                ('question_content', models.CharField(max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('choiceA', models.CharField(max_length=200, verbose_name='\u9009\u9879A')),
                ('choiceB', models.CharField(max_length=200, verbose_name='\u9009\u9879B')),
                ('choiceC', models.CharField(max_length=200, verbose_name='\u9009\u9879C')),
                ('choiceD', models.CharField(max_length=200, verbose_name='\u9009\u9879D')),
                ('answer', models.CharField(max_length=2, verbose_name='\u7b54\u6848')),
                ('explain', models.CharField(max_length=800, verbose_name='\u7b54\u6848\u89e3\u91ca')),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898',
                'verbose_name_plural': '\u9009\u62e9\u9898',
            },
        ),
        migrations.CreateModel(
            name='ProgramQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField(verbose_name='\u9898\u76ee\u7f16\u53f7')),
                ('question_content', models.CharField(max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='\u6e90\u7801\u6587\u4ef6')),
                ('url', models.CharField(default='', max_length=200, verbose_name='\u9898\u76ee\u8bb2\u89e3\u89c6\u9891\u5730\u5740')),
                ('essentials', models.CharField(max_length=500, verbose_name='\u9898\u76ee\u8981\u70b9')),
            ],
            options={
                'verbose_name': '\u7f16\u7a0b\u9898',
                'verbose_name_plural': '\u7f16\u7a0b\u9898',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u9898\u5e93\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='\u8bfe\u7a0b\u7ae0\u8282')),
            ],
            options={
                'verbose_name': '\u9898\u5e93',
                'verbose_name_plural': '\u9898\u5e93',
            },
        ),
        migrations.DeleteModel(
            name='Course_choice',
        ),
        migrations.RemoveField(
            model_name='user_choice',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_full',
            name='full_num',
        ),
        migrations.RemoveField(
            model_name='user_full',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_project',
            name='project_num',
        ),
        migrations.RemoveField(
            model_name='user_project',
            name='username',
        ),
        migrations.DeleteModel(
            name='Course_full',
        ),
        migrations.DeleteModel(
            name='Course_project',
        ),
        migrations.DeleteModel(
            name='User_choice',
        ),
        migrations.DeleteModel(
            name='User_full',
        ),
        migrations.DeleteModel(
            name='User_project',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='questionBank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.QuestionBank', verbose_name='\u6240\u5c5e\u9898\u5e93'),
        ),
    ]
