# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-11 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepractice', '0002_auto_20180111_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='programquestion',
            name='questionBank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.QuestionBank', verbose_name='\u6240\u5c5e\u9898\u5e93'),
        ),
    ]
