# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepractice', '0003_programquestion_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='complete_times',
            field=models.IntegerField(default=0, verbose_name='\u5efa\u8bae\u5b8c\u6210\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='degree',
            field=models.CharField(blank=True, choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], max_length=2, null=True, verbose_name='\u96be\u5ea6'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='onlinepractice/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
