# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepractice', '0005_questionbank_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='type',
            field=models.CharField(blank=True, choices=[('xzt', '\u9009\u62e9\u9898'), ('bct', '\u7f16\u7a0b\u9898')], max_length=5, null=True, verbose_name='\u9898\u5e93\u7c7b\u522b'),
        ),
    ]
