# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinepractice', '0006_questionbank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='detail',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u9898\u5e93\u8be6\u60c5'),
        ),
    ]
