# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-25 20:51
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0014_auto_20161113_2218'),
        ('onlinepractice', '0010_auto_20180125_0724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_auto_20161210_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8bc4\u8bba',
                'verbose_name_plural': '\u8bfe\u7a0b\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('course_name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u54a8\u8be2',
                'verbose_name_plural': '\u7528\u6237\u54a8\u8be2',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bfe\u7a0b',
                'verbose_name_plural': '\u7528\u6237\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='UserErrorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.ChoiceQuestion', verbose_name='\u9519\u9898')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9519\u9898',
                'verbose_name_plural': '\u7528\u6237\u9519\u9898',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eid')),
                ('fav_type', models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u8bfe\u7a0b\u673a\u6784'), (3, '\u8bb2\u5e08')], default=1, verbose_name='\u6536\u85cf\u7c7b\u578b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6237')),
                ('message', models.CharField(max_length=500, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_bank_id', models.IntegerField(default=0, verbose_name='\u9898\u5e93id')),
                ('practice_num', models.IntegerField(default=0, verbose_name='\u5df2\u5b8c\u6210\u6700\u540e\u9898\u76ee\u9898\u53f7')),
                ('practice_bank_correct_percent', models.IntegerField(default=0, verbose_name='\u9898\u5e93\u6b63\u786e\u7387')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4f5c\u4e1a\u60c5\u51b5',
                'verbose_name_plural': '\u7528\u6237\u4f5c\u4e1a\u60c5\u51b5',
            },
        ),
        migrations.CreateModel(
            name='UserPracticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(default='', upload_to='onlinepractice/upload/%Y/%m', verbose_name='\u7528\u6237\u6e90\u7801')),
                ('comment', DjangoUeditor.models.UEditorField(default='', verbose_name='\u8001\u5e08\u70b9\u8bc4')),
                ('level', models.CharField(choices=[('wm', '\u5b8c\u7f8e'), ('yx', '\u4f18\u79c0'), ('lh', '\u826f\u597d'), ('hg', '\u5408\u683c'), ('bhg', '\u4e0d\u5408\u683c')], max_length=8, verbose_name='\u8bc4\u5206\u7b49\u7ea7')),
                ('comment_status', models.IntegerField(choices=[(1, '\u5df2\u70b9\u8bc4'), (0, '\u672a\u70b9\u8bc4')], default=0, verbose_name='\u662f\u5426\u5df2\u7ecf\u70b9\u8bc4')),
                ('user_submit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4f5c\u4e1a\u63d0\u4ea4\u65f6\u95f4')),
                ('teacher_comment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8001\u5e08\u70b9\u8bc4\u65f6\u95f4')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.ProgramQuestion', verbose_name='\u70b9\u8bc4\u7684\u7f16\u7a0b\u9898')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u70b9\u8bc4\u8bb2\u5e08')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7684\u4f5c\u4e1a\u70b9\u8bc4',
                'verbose_name_plural': '\u7528\u6237\u7684\u4f5c\u4e1a\u70b9\u8bc4',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(default='', max_length=1000, verbose_name='\u63d0\u95ee\u5185\u5bb9')),
                ('answer', DjangoUeditor.models.UEditorField(verbose_name='\u8001\u5e08\u56de\u7b54')),
                ('question_status', models.IntegerField(choices=[(1, '\u5df2\u56de\u7b54'), (0, '\u672a\u56de\u7b54')], default=0, verbose_name='\u662f\u5426\u5df2\u7ecf\u56de\u7b54')),
                ('user_question_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u63d0\u95ee\u65f6\u95f4')),
                ('teacher_answer_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u56de\u7b54\u65f6\u95f4')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u56de\u7b54\u8bb2\u5e08')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u95ee\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u95ee\u9898\u56de\u7b54',
                'verbose_name_plural': '\u7528\u6237\u95ee\u9898\u56de\u7b54',
            },
        ),
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u8bb2\u5e08')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8bb2\u5e08\u7528\u6237\u8868',
                'verbose_name_plural': '\u8bb2\u5e08\u7528\u6237\u8868',
            },
        ),
    ]
