# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-17 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinepractice', '0007_questionbank_detail'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserErrorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinepractice.ChoiceQuestion', verbose_name='\u9519\u9898')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9519\u9898',
                'verbose_name_plural': '\u7528\u6237\u9519\u9898',
            },
        ),
    ]
